# Generated by Django 4.2.6 on 2023-11-12 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jewelGleamer', '0002_alter_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
