# Generated by Django 4.2.6 on 2023-11-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='role_changed',
            field=models.BooleanField(default=False),
        ),
    ]
